var hierarchy =
[
    [ "kobuki::AccelerationLimiter", "classkobuki_1_1_acceleration_limiter.html", null ],
    [ "kobuki::Battery", "classkobuki_1_1_battery.html", null ],
    [ "kobuki::BumperEvent", "structkobuki_1_1_bumper_event.html", null ],
    [ "kobuki::ButtonEvent", "structkobuki_1_1_button_event.html", null ],
    [ "kobuki::CliffEvent", "structkobuki_1_1_cliff_event.html", null ],
    [ "kobuki::Command::Data", "structkobuki_1_1_command_1_1_data.html", null ],
    [ "kobuki::Current::Data", "structkobuki_1_1_current_1_1_data.html", null ],
    [ "kobuki::DockIR::Data", "structkobuki_1_1_dock_i_r_1_1_data.html", null ],
    [ "kobuki::Eeprom::Data", "structkobuki_1_1_eeprom_1_1_data.html", null ],
    [ "kobuki::Firmware::Data", "structkobuki_1_1_firmware_1_1_data.html", null ],
    [ "kobuki::GpInput::Data", "structkobuki_1_1_gp_input_1_1_data.html", null ],
    [ "kobuki::Hardware::Data", "structkobuki_1_1_hardware_1_1_data.html", null ],
    [ "kobuki::Inertia::Data", "structkobuki_1_1_inertia_1_1_data.html", null ],
    [ "kobuki::ThreeAxisGyro::Data", "structkobuki_1_1_three_axis_gyro_1_1_data.html", null ],
    [ "kobuki::Cliff::Data", "structkobuki_1_1_cliff_1_1_data.html", null ],
    [ "kobuki::UniqueDeviceID::Data", "structkobuki_1_1_unique_device_i_d_1_1_data.html", null ],
    [ "kobuki::ControllerInfo::Data", "structkobuki_1_1_controller_info_1_1_data.html", null ],
    [ "kobuki::CoreSensors::Data", "structkobuki_1_1_core_sensors_1_1_data.html", null ],
    [ "kobuki::DiffDrive", "classkobuki_1_1_diff_drive.html", null ],
    [ "kobuki::DigitalOutput", "structkobuki_1_1_digital_output.html", null ],
    [ "kobuki::DockDrive", "classkobuki_1_1_dock_drive.html", null ],
    [ "kobuki::DockStationIRState", "structkobuki_1_1_dock_station_i_r_state.html", null ],
    [ "kobuki::EventManager", "classkobuki_1_1_event_manager.html", null ],
    [ "kobuki::CoreSensors::Flags", "structkobuki_1_1_core_sensors_1_1_flags.html", null ],
    [ "kobuki::Header", "classkobuki_1_1_header.html", null ],
    [ "kobuki::InputEvent", "structkobuki_1_1_input_event.html", null ],
    [ "kobuki::Kobuki", "classkobuki_1_1_kobuki.html", null ],
    [ "KobukiManager", "class_kobuki_manager.html", null ],
    [ "kobuki::PacketFinderBase", "classkobuki_1_1_packet_finder_base.html", [
      [ "kobuki::PacketFinder", "classkobuki_1_1_packet_finder.html", null ]
    ] ],
    [ "kobuki::Parameters", "classkobuki_1_1_parameters.html", null ],
    [ "packet_handler::payloadBase", "classpacket__handler_1_1payload_base.html", [
      [ "kobuki::Cliff", "classkobuki_1_1_cliff.html", null ],
      [ "kobuki::Command", "classkobuki_1_1_command.html", null ],
      [ "kobuki::ControllerInfo", "classkobuki_1_1_controller_info.html", null ],
      [ "kobuki::CoreSensors", "classkobuki_1_1_core_sensors.html", null ],
      [ "kobuki::Current", "classkobuki_1_1_current.html", null ],
      [ "kobuki::DockIR", "classkobuki_1_1_dock_i_r.html", null ],
      [ "kobuki::Eeprom", "classkobuki_1_1_eeprom.html", null ],
      [ "kobuki::Firmware", "classkobuki_1_1_firmware.html", null ],
      [ "kobuki::GpInput", "classkobuki_1_1_gp_input.html", null ],
      [ "kobuki::Hardware", "classkobuki_1_1_hardware.html", null ],
      [ "kobuki::Inertia", "classkobuki_1_1_inertia.html", null ],
      [ "kobuki::ThreeAxisGyro", "classkobuki_1_1_three_axis_gyro.html", null ],
      [ "kobuki::UniqueDeviceID", "classkobuki_1_1_unique_device_i_d.html", null ]
    ] ],
    [ "kobuki::PowerEvent", "structkobuki_1_1_power_event.html", null ],
    [ "Rb2Vw", "class_rb2_vw.html", null ],
    [ "kobuki::RobotDockingState", "structkobuki_1_1_robot_docking_state.html", null ],
    [ "kobuki::RobotEvent", "structkobuki_1_1_robot_event.html", null ],
    [ "kobuki::union_sint16", "unionkobuki_1_1union__sint16.html", null ],
    [ "kobuki::VersionInfo", "classkobuki_1_1_version_info.html", null ],
    [ "kobuki::WheelEvent", "structkobuki_1_1_wheel_event.html", null ]
];